Select * from sale_report;

--1. Total Sales Revenue
--Calculate the total revenue generated from all sales.

SELECT SUM(price_total) AS total_revenue
FROM sale_report;
---------------------------------------------------------------------------------------------------------
--2. Total Revenue by Product
--Calculate the total revenue for each product.

SELECT product_id_name, SUM(price_total) AS total_revenue
FROM sale_report
GROUP BY product_id_name
ORDER BY total_revenue DESC;

----------------------------------------------------------------------------------------------------------------
--3. Total Revenue by Branch
--Calculate the total revenue for each branch .

SELECT name, SUM(price_total) AS total_revenue
FROM sale_report
GROUP BY name
ORDER BY total_revenue DESC;

---------------------------------------------------------------------------------------------------------------
--4. Average Sale Price per Product
--Calculate the average sale price for each product.

SELECT product_id_name, AVG(price_total) AS avg_sale_price
FROM sale_report
GROUP BY product_id_name
ORDER BY avg_sale_price DESC;

------------------------------------------------------------------------------------------------------------
--5. Total Quantity Sold by Product
--Calculate the total quantity sold for each product.

SELECT product_id_name, SUM(product_uom_qty) AS total_quantity_sold
FROM sale_report
GROUP BY product_id_name
ORDER BY total_quantity_sold DESC;

------------------------------------------------------------------------------------------------------------
--6. Total Revenue by Sales Team
--Calculate the total revenue generated by each sales team.

SELECT team_id_name, SUM(price_total) AS total_revenue
FROM sale_report
GROUP BY team_id_name
ORDER BY total_revenue DESC;

------------------------------------------------------------------------------------------------------------
--7. Top 5 Products by Revenue
--Identify the top 5 products by revenue.

SELECT Top 5 product_id_name, SUM(price_total) AS total_revenue
FROM sale_report
GROUP BY product_id_name
ORDER BY total_revenue DESC;

-----------------------------------------------------------------------------------------------------------
--8. Total Revenue by Date
--Calculate the total revenue for each date.

SELECT date, SUM(price_total) AS total_revenue
FROM sale_report
GROUP BY date
ORDER BY date;

----------------------------------------------------------------------------------------------------------
--9. Total Revenue by Product Category
--Calculate the total revenue for each product category.

SELECT categ_id_name, SUM(price_total) AS total_revenue
FROM sale_report
GROUP BY categ_id_name
ORDER BY total_revenue DESC;

------------------------------------------------------------------------------------------------------------
--10. Total Discount Amount
--Calculate the total discount amount applied across all sales.

SELECT SUM(discount_amount) AS total_discount
FROM sale_report;

------------------------------------------------------------------------------------------------------------
--11. Average Discount Percentage
--Calculate the average discount percentage applied across all sales.

SELECT AVG(discount) AS avg_discount_percentage
FROM sale_report;

-----------------------------------------------------------------------------------------------------------
--12. Total Revenue by User
--Calculate the total revenue generated by each user.

SELECT user_id_name, SUM(price_total) AS total_revenue
FROM sale_report
GROUP BY user_id_name
ORDER BY total_revenue DESC;

----------------------------------------------------------------------------------------------------------
--13. Total Revenue by Warehouse
--Calculate the total revenue generated by each warehouse.

SELECT warehouse_id_name, SUM(price_total) AS total_revenue
FROM sale_report
GROUP BY warehouse_id_name
ORDER BY total_revenue DESC;

----------------------------------------------------------------------------------------------------------
--14. Total Revenue by Campaign
--Calculate the total revenue generated by each campaign.

SELECT campaign_id_name, SUM(price_total) AS total_revenue
FROM sale_report
GROUP BY campaign_id_name
ORDER BY total_revenue DESC;
-----------------------------------------------------------------------------------------------------------

--15. Total Revenue by Partner
--Calculate the total revenue generated by each partner.

SELECT partner_name, SUM(price_total) AS total_revenue
FROM sale_report
GROUP BY partner_name
ORDER BY total_revenue DESC;

---------------------------------------------------------------------------------------------------------
--16. Total Revenue by Product Template
--Calculate the total revenue for each product template.

SELECT product_tmpl_id_name, SUM(price_total) AS total_revenue
FROM sale_report
GROUP BY product_tmpl_id_name
ORDER BY total_revenue DESC;

-----------------------------------------------------------------------------------------------------------
--17. Total Revenue by Industry
--Calculate the total revenue for each industry.

SELECT industry_id, SUM(price_total) AS total_revenue
FROM sale_report
GROUP BY industry_id
ORDER BY total_revenue DESC;

----------------------------------------------------------------------------------------------------------
--18. Total Revenue by Country
--Calculate the total revenue for each country.


SELECT country_id, SUM(price_total) AS total_revenue
FROM sale_report
GROUP BY country_id
ORDER BY total_revenue DESC;


----------------------------------------------------------------------------------------------------------
--19. Total Revenue by Medium
--Calculate the total revenue generated by each medium.


SELECT medium_id_name, SUM(price_total) AS total_revenue
FROM sale_report
GROUP BY medium_id_name
ORDER BY total_revenue DESC;

--------------------------------------------------------------------------------------------------------------
--20. Total Revenue by Source
--Calculate the total revenue generated by each source.


SELECT source_id_name, SUM(price_total) AS total_revenue
FROM sale_report
GROUP BY source_id_name
ORDER BY total_revenue DESC;

---------------------------------------------------------------------------------------------------------
--21. Total Revenue by Order
--Calculate the total revenue for each order.


SELECT order_id, SUM(price_total) AS total_revenue
FROM sale_report
GROUP BY order_id
ORDER BY total_revenue DESC;

---------------------------------------------------------------------------------------------------------
--22. Total Revenue by State
--Calculate the total revenue for each state.


SELECT state, SUM(price_total) AS total_revenue
FROM sale_report
GROUP BY state
ORDER BY total_revenue DESC;

----------------------------------------------------------------------------------------------------------
--23. Total Revenue by Commercial Partner
--Calculate the total revenue generated by each commercial partner.


SELECT commercial_partner_id_name, SUM(price_total) AS total_revenue
FROM sale_report
GROUP BY commercial_partner_id_name
ORDER BY total_revenue DESC;

-----------------------------------------------------------------------------------------------------------
--24. Total Revenue by Pricelist
--Calculate the total revenue generated by each pricelist.


SELECT pricelist_id_name, SUM(price_total) AS total_revenue
FROM sale_report
GROUP BY pricelist_id_name
ORDER BY total_revenue DESC;

-----------------------------------------------------------------------------------------------------------
--25. Total Revenue by Analytic Account
--Calculate the total revenue generated by each analytic account.


SELECT analytic_account_id, SUM(price_total) AS total_revenue
FROM sale_report
GROUP BY analytic_account_id
ORDER BY total_revenue DESC;
